version: "3"

services:
  kong-database:  
    restart: always
    image: cassandra:3
    container_name: kong-database
    ports:
      - 9042:9042 
      - 7000:7000
    volumes:
      - "db-data:/var/lib/cassandra"
    networks:
      - kong-net

  kong-migrations:  
    restart: on-failure
    image: kong:0.14.1
    container_name: kong-migrations
    command: kong migrations up
    environment:
      - DATABASE=cassandra
      - KONG_DATABASE=cassandra
      - KONG_CASSANDRA_CONTACT_POINTS=kong-database
      - KONG_DB_UPDATE_PROPAGATION=5
    networks:
      - kong-net
    depends_on:
      - kong-database

  kong:  
    restart: always
    image: kong:0.14.1
    container_name: kong
    ports:
      - 80:8000
      - 443:8443
      - 8001:8001
      - 8444:8444
    environment:
      - DATABASE=cassandra
      - KONG_DATABASE=cassandra
      - KONG_CASSANDRA_CONTACT_POINTS=kong-database
      - KONG_DB_UPDATE_PROPAGATION=5
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_ADMIN_LISTEN_SSL=0.0.0.0:8444
    networks:
      - kong-net

  kong-dashboard:  
    restart: always
    image: pgbi/kong-dashboard:v3.5.0
    container_name: kong-dashboard
    command: "start --kong-url http://kong:8001"
    ports:
      - "8080:8080"
    networks:
      - kong-net

volumes:
  db-data:

networks:
  kong-net:
    driver: bridge